site_name: Software Engineering

theme: readthedocs

nav:
  - Home: index.md
  - Best Practice: ./best_practice/index.md
  - Technical: ./technical/index.md
  - Artifact Templates: ./artifact_templates/index.md
  - About: ./about/index.md
  - Glossary: ./glossary.md