site_name: Software Engineering

theme: readthedocs

nav:
  - Home: index.md
  - Best Practice: ./best_practice/index.md
  - Technical: ./technical/index.md
  - Templates: ./templates/index.md
  - About: ./about/index.md